/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import com.mycompany.quanlydatban.GUI.PlaceholderSupport;
import com.mycompany.quanlydatban.dao.BanAnDAO;
import com.mycompany.quanlydatban.dao.DanhMucMonAnDAO;
import com.mycompany.quanlydatban.dao.MonAnDAO;
import com.mycompany.quanlydatban.entity.BanAn;
import com.mycompany.quanlydatban.entity.DanhMucMonAn;
import com.mycompany.quanlydatban.entity.EnumTrangThaiBan;
import com.mycompany.quanlydatban.entity.MonAn;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ACER
 */
public class BanAn_GUI extends javax.swing.JPanel {

    Color color_bg = Color.decode("#00405d");
    DefaultTableModel model_dsBan;
    JTable table_dsBan;
    
    private DefaultTableModel dtm;
    private List<BanAn> list = BanAnDAO.getAllBan();

    /**
     * Creates new form MonAn_GUI
     */

    public BanAn_GUI() {
        initComponents();
        Dimension size = new Dimension(1019, 100);
        setSize(size);

        jb_sua.setBackground(color_bg);
        jb_them.setBackground(color_bg);
        jb_tim.setBackground(color_bg);
        jb_xoa.setBackground(color_bg);
        PlaceholderSupport placeholderSupport = new PlaceholderSupport();
        placeholderSupport.addPlaceholder(txt_tim, " Nhập mã bàn để tìm kiếm");

        //        bảng ds món đã đặt
        String columnName[] = {"Mã bàn", "Số lượng ghế", "Ghi chú"};
        model_dsBan = new DefaultTableModel(columnName, 0);
        table_dsBan = new JTable(model_dsBan);
        table_dsBan.setBackground(new Color(255, 255, 255));
        table_dsBan.setFont(new java.awt.Font("JetBrains Mono", 0, 14));
        JScrollPane jScrollPane_dsBan = new JScrollPane(table_dsBan);
        table_dsBan.setOpaque(true);
        dtm = (DefaultTableModel)table_dsBan.getModel();
        // Lấy header của bảng và cài đặt font cho header
        JTableHeader tableHeader = table_dsBan.getTableHeader();
        tableHeader.setFont(new Font("JetBrains Mono", Font.BOLD, 12));
        tableHeader.setBackground(color_bg);
        tableHeader.setForeground(Color.WHITE);
        dataToTable();

        jp_tableBan.add(jScrollPane_dsBan, BorderLayout.CENTER);
    }

    public void dataToTable(){
        for(BanAn b: list){
            dtm.addRow(new Object[]{
            b.getMaBan(),
            b.getSoLuongGhe(),
            b.getGhiChu()
            });
        }
    }
    
    public void  xoaTrang()
    {
        txt_maBan.setText("");
        txt_soLuongGhe.setText("");
        txt_ghiChu.setText("");
        txt_tim.setText("");
    }     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_food = new javax.swing.JPanel();
        l_maF = new javax.swing.JLabel();
        txt_soLuongGhe = new javax.swing.JTextField();
        l_gia = new javax.swing.JLabel();
        jp_button = new javax.swing.JPanel();
        jb_sua = new javax.swing.JButton();
        jb_xoa = new javax.swing.JButton();
        jb_them = new javax.swing.JButton();
        txt_ghiChu = new javax.swing.JTextField();
        l_maF1 = new javax.swing.JLabel();
        txt_maBan = new javax.swing.JTextField();
        jp_table = new javax.swing.JPanel();
        txt_tim = new javax.swing.JTextField();
        jb_tim = new javax.swing.JButton();
        jp_tableBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1019, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_food.setBackground(new java.awt.Color(255, 255, 255));
        jp_food.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jp_food.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_maF.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_maF.setText("Ghi chú:");
        jp_food.add(l_maF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 83, 30));

        txt_soLuongGhe.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_soLuongGhe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jp_food.add(txt_soLuongGhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 210, 30));

        l_gia.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_gia.setText("Số lượng ghế:");
        jp_food.add(l_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 30));

        jp_button.setBackground(new java.awt.Color(255, 255, 255));

        jb_sua.setBackground(new java.awt.Color(22, 78, 180));
        jb_sua.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_sua.setForeground(new java.awt.Color(255, 255, 255));
        jb_sua.setText("SỬA");
        jb_sua.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suaActionPerformed(evt);
            }
        });

        jb_xoa.setBackground(new java.awt.Color(22, 78, 180));
        jb_xoa.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_xoa.setForeground(new java.awt.Color(255, 255, 255));
        jb_xoa.setText("XÓA");
        jb_xoa.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_xoaActionPerformed(evt);
            }
        });

        jb_them.setBackground(new java.awt.Color(22, 78, 180));
        jb_them.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_them.setForeground(new java.awt.Color(255, 255, 255));
        jb_them.setText("THÊM");
        jb_them.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_buttonLayout = new javax.swing.GroupLayout(jp_button);
        jp_button.setLayout(jp_buttonLayout);
        jp_buttonLayout.setHorizontalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jp_buttonLayout.setVerticalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jb_them, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jp_food.add(jp_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 550, 50));

        txt_ghiChu.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_ghiChu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jp_food.add(txt_ghiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 210, 30));

        l_maF1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_maF1.setText("Mã bàn ăn:");
        jp_food.add(l_maF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 83, 30));

        txt_maBan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_maBan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jp_food.add(txt_maBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 210, 30));

        add(jp_food, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 770, 160));

        jp_table.setBackground(new java.awt.Color(255, 255, 255));

        txt_tim.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txt_tim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb_tim.setBackground(new java.awt.Color(22, 78, 180));
        jb_tim.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jb_tim.setForeground(new java.awt.Color(255, 255, 255));
        jb_tim.setText("Tìm kiếm");
        jb_tim.setBorder(null);
        jb_tim.setPreferredSize(new java.awt.Dimension(30, 30));
        jb_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_tableLayout = new javax.swing.GroupLayout(jp_table);
        jp_table.setLayout(jp_tableLayout);
        jp_tableLayout.setHorizontalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(915, Short.MAX_VALUE))
        );
        jp_tableLayout.setVerticalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(390, 390, 390))
        );

        add(jp_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 60));

        jp_tableBan.setLayout(new java.awt.BorderLayout());
        add(jp_tableBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 1000, 290));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ BÀN ĂN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jb_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_timActionPerformed
        // TODO add your handling code here:
        String maB = txt_tim.getText();
        BanAnDAO ban_d = new BanAnDAO();
        BanAn b = ban_d.tim(maB);
        if(b!=null){
            dtm.setRowCount(0);
            dtm.addRow(new Object[]{
                b.getMaBan(),
                b.getSoLuongGhe(),
                b.getGhiChu()
            });
        } 
         else if(txt_tim.getText().equals(""))
            {
                dtm.setRowCount(0);
                dataToTable();
            }
            else if(b== null) {
                JOptionPane.showMessageDialog(this,"Không tìm thấy bàn ăn này");
        
        }
    }//GEN-LAST:event_jb_timActionPerformed

    private void jb_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suaActionPerformed
        // TODO add your handling code here:
        String maB = txt_maBan.getText();
        BanAnDAO ban_d = new BanAnDAO();
        BanAn b = ban_d.tim(maB);
        if (b != null) {
            int sl = 0;
            try {
            sl=Integer.parseInt(txt_soLuongGhe.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng ghế không hợp lệ! Vui lòng nhập một số.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return; 
        }
            String ghichu = txt_ghiChu.getText();         
            b.setSoLuongGhe(sl);
            b.setGhiChu(ghichu);
            ban_d.suaBan(b); 
            dtm.setRowCount(0);
            list = BanAnDAO.getAllBan();
            dataToTable();
            xoaTrang();
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            
        }else if(b==null){
            dtm.setRowCount(0);
            list = BanAnDAO.getAllBan();
            dataToTable();
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }
    }//GEN-LAST:event_jb_suaActionPerformed

    private void jb_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_themActionPerformed
        String maBan = txt_maBan.getText();
        String slGhe = txt_soLuongGhe.getText();
        String ghiChu = txt_ghiChu.getText();

        if (!slGhe.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số lượng ghế phải là số dương", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int soLuongGhe = Integer.parseInt(slGhe);
        BanAn ban = new BanAn(maBan, soLuongGhe, EnumTrangThaiBan.TRONG, ghiChu);

        if (BanAnDAO.themBan(ban)) {
            txt_maBan.setText("");
            JOptionPane.showMessageDialog(this, "Thêm thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_themActionPerformed

    private void jb_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_xoaActionPerformed
        // TODO add your handling code here:
        int r = table_dsBan.getSelectedRow();
        if (r != -1) {
            int result = JOptionPane.showOptionDialog(
                    this, // Parent component
                    "Bạn có chắc chắn muốn xoá bàn này không?", // Message
                    "Thông báo", // Title
                    JOptionPane.YES_NO_OPTION, // Option type (Yes/No buttons)
                    JOptionPane.QUESTION_MESSAGE, // Message type (icon)
                    null, // Icon (null means default)
                    null, // Possible options (null uses default Yes/No)
                    null // Default option (null means first button, "Yes")
            );
            if (result == JOptionPane.YES_OPTION) {
                BanAnDAO ban_d = new BanAnDAO();
                if (ban_d.xoaBan(dtm.getValueAt(r, 0).toString())) {
                    dtm.setRowCount(0);
                    list=BanAnDAO.getAllBan();
                    dataToTable();
                    xoaTrang();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                }
            }
        } else
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn để xoá");
        
    }//GEN-LAST:event_jb_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_sua;
    private javax.swing.JButton jb_them;
    private javax.swing.JButton jb_tim;
    private javax.swing.JButton jb_xoa;
    private javax.swing.JPanel jp_button;
    private javax.swing.JPanel jp_food;
    private javax.swing.JPanel jp_table;
    private javax.swing.JPanel jp_tableBan;
    private javax.swing.JLabel l_gia;
    private javax.swing.JLabel l_maF;
    private javax.swing.JLabel l_maF1;
    private javax.swing.JTextField txt_ghiChu;
    private javax.swing.JTextField txt_maBan;
    private javax.swing.JTextField txt_soLuongGhe;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables

}
