/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author ACER
 */
public class BanAn_GUI extends javax.swing.JPanel {
    Color color_bg = Color.decode("#00405d");
    /**
     * Creates new form MonAn_GUI
     */
    public BanAn_GUI() {
        initComponents();
        Dimension size = new Dimension(1019,100);
        setSize(size);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(255, 255, 255));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setBackground(new Color(255, 255, 255));
        jTable1.setSelectionMode(0);
        jb_sua.setBackground(color_bg);
        jb_them.setBackground(color_bg);
        jb_tim.setBackground(color_bg);
        jb_xoa.setBackground(color_bg);
        PlaceholderSupport placeholderSupport = new PlaceholderSupport();
        placeholderSupport.addPlaceholder(jt_tim," Nhập mã bàn để tìm kiếm");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_food = new javax.swing.JPanel();
        l_maBan = new javax.swing.JLabel();
        l_ghiChu = new javax.swing.JLabel();
        jt_maBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_ghiChu = new javax.swing.JTextArea();
        l_soLuong = new javax.swing.JLabel();
        jt_soLuong = new javax.swing.JTextField();
        jp_button = new javax.swing.JPanel();
        jb_them = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        jb_sua = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        jb_xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jp_table = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jt_tim = new javax.swing.JTextField();
        jb_tim = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(598, 100));

        jp_food.setBackground(new java.awt.Color(255, 255, 255));
        jp_food.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "QUẢN LÝ BÀN ĂN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        l_maBan.setForeground(new java.awt.Color(0, 0, 0));
        l_maBan.setText("Mã bàn:");

        l_ghiChu.setForeground(new java.awt.Color(0, 0, 0));
        l_ghiChu.setText("Ghi chú:");

        jt_maBan.setBackground(new java.awt.Color(255, 255, 255));
        jt_maBan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        text_ghiChu.setBackground(new java.awt.Color(255, 255, 255));
        text_ghiChu.setColumns(1);
        text_ghiChu.setRows(3);
        text_ghiChu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jScrollPane1.setViewportView(text_ghiChu);

        l_soLuong.setBackground(new java.awt.Color(255, 255, 255));
        l_soLuong.setForeground(new java.awt.Color(0, 0, 0));
        l_soLuong.setText("Số lượng:");

        jt_soLuong.setBackground(new java.awt.Color(255, 255, 255));
        jt_soLuong.setForeground(new java.awt.Color(0, 0, 0));
        jt_soLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jp_button.setBackground(new java.awt.Color(255, 255, 255));

        jb_them.setBackground(new java.awt.Color(22, 78, 180));
        jb_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_them.setForeground(new java.awt.Color(255, 255, 255));
        jb_them.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\add.png")); // NOI18N
        jb_them.setText("THÊM");
        jb_them.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_themActionPerformed(evt);
            }
        });

        jb_sua.setBackground(new java.awt.Color(22, 78, 180));
        jb_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_sua.setForeground(new java.awt.Color(255, 255, 255));
        jb_sua.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\fix.png")); // NOI18N
        jb_sua.setText("SỬA");
        jb_sua.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suaActionPerformed(evt);
            }
        });

        jb_xoa.setBackground(new java.awt.Color(22, 78, 180));
        jb_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_xoa.setForeground(new java.awt.Color(255, 255, 255));
        jb_xoa.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\delete.png")); // NOI18N
        jb_xoa.setText("XÓA");
        jb_xoa.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_buttonLayout = new javax.swing.GroupLayout(jp_button);
        jp_button.setLayout(jp_buttonLayout);
        jp_buttonLayout.setHorizontalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_buttonLayout.setVerticalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\banan.jpg")); // NOI18N

        javax.swing.GroupLayout jp_foodLayout = new javax.swing.GroupLayout(jp_food);
        jp_food.setLayout(jp_foodLayout);
        jp_foodLayout.setHorizontalGroup(
            jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_foodLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jp_foodLayout.createSequentialGroup()
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_foodLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_maBan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_ghiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jt_maBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(jt_soLuong, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_foodLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_foodLayout.setVerticalGroup(
            jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_foodLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_maBan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_maBan))
                .addGap(33, 33, 33)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_soLuong))
                .addGap(27, 27, 27)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_ghiChu))
                .addGap(55, 55, 55)
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jp_table.setBackground(new java.awt.Color(255, 255, 255));
        jp_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Số lượng", "Trạng thái", "Ghi chú"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jt_tim.setBackground(new java.awt.Color(255, 255, 255));
        jt_tim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_timActionPerformed(evt);
            }
        });

        jb_tim.setBackground(new java.awt.Color(22, 78, 180));
        jb_tim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_tim.setForeground(new java.awt.Color(255, 255, 255));
        jb_tim.setText("Tìm kiếm");
        jb_tim.setBorder(null);
        jb_tim.setPreferredSize(new java.awt.Dimension(30, 30));
        jb_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_tableLayout = new javax.swing.GroupLayout(jp_table);
        jp_table.setLayout(jp_tableLayout);
        jp_tableLayout.setHorizontalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_tableLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_tableLayout.setVerticalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_food, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_food, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_suaActionPerformed

    private void jb_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_timActionPerformed

    private void jt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_timActionPerformed

    private void jb_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_themActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_themActionPerformed

    private void jb_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_xoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_sua;
    private javax.swing.JButton jb_them;
    private javax.swing.JButton jb_tim;
    private javax.swing.JButton jb_xoa;
    private javax.swing.JPanel jp_button;
    private javax.swing.JPanel jp_food;
    private javax.swing.JPanel jp_table;
    private javax.swing.JTextField jt_maBan;
    private javax.swing.JTextField jt_soLuong;
    private javax.swing.JTextField jt_tim;
    private javax.swing.JLabel l_ghiChu;
    private javax.swing.JLabel l_maBan;
    private javax.swing.JLabel l_soLuong;
    private javax.swing.JTextArea text_ghiChu;
    // End of variables declaration//GEN-END:variables
}
