/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.border.LineBorder;

/**
 *
 * @author ACER
 */
public class MainGUI extends javax.swing.JFrame {

	private int currentIndex;
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        setLayout(new BorderLayout());
        add(jp_menu, BorderLayout.WEST);
        add(jp_root, BorderLayout.CENTER);
        
        jp_root.setLayout(new BorderLayout());
        jp_root.add(btn_main_img, BorderLayout.CENTER);
        jp_root.add(jp_title, BorderLayout.NORTH);

        // Lấy kích thước màn hình hiện tại
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;

        // Thiết lập chiều rộng của jp_menu bằng 1/5 chiều rộng màn hình
        jp_menu.setPreferredSize(new Dimension(screenWidth / 5, screenHeight));
        jp_menu.setBackground(new java.awt.Color(255, 255, 255));
        
        jp_root.setBackground(new Color(200, 200, 200));  // Màu nền xám nhạt
        jp_root.setPreferredSize(new Dimension((screenWidth * 4) / 5,screenHeight-150));

        // Các thuộc tính tắt viền của Icon và focus
        logo.setContentAreaFilled(false);  // Tắt màu nền của nút
        logo.setFocusPainted(false);  // Tắt viền khi nút được focus
        logo.setOpaque(false);  // Đảm bảo nút trong suốt
        logo.setBorderPainted(true);  // Hiển thị viền của JButton, nhưng không có viền của Icon

        timeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        // Tạo định dạng cho ngày và giờ
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy | HH:mm:ss");

        // Tạo Timer để cập nhật thời gian mỗi giây
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Lấy thời gian hiện tại
                LocalDateTime now = LocalDateTime.now();
                // Định dạng và đặt thời gian vào JLabel
                timeLabel.setText(now.format(formatter));
            }
        });
        timer.start();

        labelTenNV.setText("Xin chào, Võ Huy Tưởng!");

        jp_menu.setOpaque(true);  // Đảm bảo JPanel không trong suốt
        
        btn_main_img.setIcon(new javax.swing.ImageIcon("D:\\PTUD\\QuanLyDatBan\\QuanLyDatBan\\QuanLyDatBan\\src\\main\\java\\img\\main3.jpg"));
        currentIndex=0;
        String main[]=new String[] {"D:\\PTUD\\QuanLyDatBan\\QuanLyDatBan\\QuanLyDatBan\\src\\main\\java\\img\\main3.jpg"
                ,"D:\\PTUD\\QuanLyDatBan\\QuanLyDatBan\\QuanLyDatBan\\src\\main\\java\\img\\main1.jpg",
                "D:\\PTUD\\QuanLyDatBan\\QuanLyDatBan\\QuanLyDatBan\\src\\main\\java\\img\\main2.jpg"
        };
        Timer timer1 = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                currentIndex = (currentIndex + 1) % 3;
		btn_main_img.setIcon(new ImageIcon(main[currentIndex]));
            }
        });
        timer1.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp_menu = new javax.swing.JPanel();
        logo = new javax.swing.JButton();
        labelTenNV = new javax.swing.JLabel();
        menuItem_BanAn = new javax.swing.JButton();
        menuItem_TaiKhoan = new javax.swing.JButton();
        menuItem_DatBan = new javax.swing.JButton();
        menuItem_HoaDon = new javax.swing.JButton();
        menuItem_MonAn = new javax.swing.JButton();
        menuItem_NhanVien = new javax.swing.JButton();
        jp_root = new javax.swing.JPanel();
        btn_main_img = new javax.swing.JButton();
        jp_title = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_menu.setBackground(new java.awt.Color(255, 255, 255));
        jp_menu.setForeground(new java.awt.Color(51, 102, 0));
        jp_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon("D:\\PTUD\\QuanLyDatBan\\QuanLyDatBan\\QuanLyDatBan\\src\\main\\java\\img\\logo.jpg")); // NOI18N
        logo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 102, 0)));
        logo.setBorderPainted(false);
        logo.setContentAreaFilled(false);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        jp_menu.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 120));

        labelTenNV.setBackground(new java.awt.Color(255, 255, 255));
        labelTenNV.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        labelTenNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTenNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 102, 0)));
        jp_menu.add(labelTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 40));

        menuItem_BanAn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItem_BanAn.setForeground(new java.awt.Color(0, 102, 0));
        menuItem_BanAn.setText("Bàn Ăn");
        menuItem_BanAn.setPreferredSize(new java.awt.Dimension(72, 30));
        menuItem_BanAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_BanAnActionPerformed(evt);
            }
        });
        jp_menu.add(menuItem_BanAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 30));

        menuItem_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItem_TaiKhoan.setForeground(new java.awt.Color(0, 102, 0));
        menuItem_TaiKhoan.setText("Tài Khoản");
        menuItem_TaiKhoan.setPreferredSize(new java.awt.Dimension(72, 30));
        jp_menu.add(menuItem_TaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, 30));

        menuItem_DatBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItem_DatBan.setForeground(new java.awt.Color(0, 102, 0));
        menuItem_DatBan.setText("Đặt Bàn");
        menuItem_DatBan.setPreferredSize(new java.awt.Dimension(72, 30));
        menuItem_DatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_DatBanActionPerformed(evt);
            }
        });
        jp_menu.add(menuItem_DatBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 30));

        menuItem_HoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItem_HoaDon.setForeground(new java.awt.Color(0, 102, 0));
        menuItem_HoaDon.setText("Hóa Đơn");
        menuItem_HoaDon.setPreferredSize(new java.awt.Dimension(72, 30));
        menuItem_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_HoaDonActionPerformed(evt);
            }
        });
        jp_menu.add(menuItem_HoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 30));

        menuItem_MonAn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItem_MonAn.setForeground(new java.awt.Color(0, 102, 0));
        menuItem_MonAn.setText("Món Ăn");
        menuItem_MonAn.setPreferredSize(new java.awt.Dimension(72, 30));
        jp_menu.add(menuItem_MonAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 30));

        menuItem_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuItem_NhanVien.setForeground(new java.awt.Color(0, 102, 0));
        menuItem_NhanVien.setText("Nhân Viên");
        menuItem_NhanVien.setPreferredSize(new java.awt.Dimension(72, 30));
        jp_menu.add(menuItem_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, 30));

        getContentPane().add(jp_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 440));

        timeLabel.setBackground(new java.awt.Color(255, 255, 255));
        timeLabel.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        timeLabel.setIcon(new javax.swing.ImageIcon("D:\\PTUD\\QuanLyDatBan\\QuanLyDatBan\\QuanLyDatBan\\src\\main\\java\\img\\Double-J-Design-Origami-Colored-Pencil-Green-clock.24.png")); // NOI18N
        timeLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 102, 0)));

        javax.swing.GroupLayout jp_titleLayout = new javax.swing.GroupLayout(jp_title);
        jp_title.setLayout(jp_titleLayout);
        jp_titleLayout.setHorizontalGroup(
            jp_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_titleLayout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_titleLayout.setVerticalGroup(
            jp_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_rootLayout = new javax.swing.GroupLayout(jp_root);
        jp_root.setLayout(jp_rootLayout);
        jp_rootLayout.setHorizontalGroup(
            jp_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_rootLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(btn_main_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jp_rootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jp_rootLayout.setVerticalGroup(
            jp_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_rootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_main_img, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jp_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 370, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void menuItem_BanAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_BanAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_BanAnActionPerformed

    private void menuItem_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_HoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_HoaDonActionPerformed

    private void menuItem_DatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_DatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_DatBanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_main_img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jp_menu;
    private javax.swing.JPanel jp_root;
    private javax.swing.JPanel jp_title;
    private javax.swing.JLabel labelTenNV;
    private javax.swing.JButton logo;
    private javax.swing.JButton menuItem_BanAn;
    private javax.swing.JButton menuItem_DatBan;
    private javax.swing.JButton menuItem_HoaDon;
    private javax.swing.JButton menuItem_MonAn;
    private javax.swing.JButton menuItem_NhanVien;
    private javax.swing.JButton menuItem_TaiKhoan;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
