/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import com.mycompany.quanlydatban.GUI.PlaceholderSupport;
import com.mycompany.quanlydatban.dao.DanhMucMonAnDAO;
import com.mycompany.quanlydatban.dao.MonAnDAO;
import com.mycompany.quanlydatban.entity.DanhMucMonAn;
import com.mycompany.quanlydatban.entity.MonAn;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MonAnGUI extends javax.swing.JPanel {

    Color color_bg = Color.decode("#00405d");
    private String urlAnh;
    HashMap<String, DanhMucMonAn> danhMuc;

    /**
     * Creates new form MonAn_GUI
     */
    public MonAnGUI() {
        initComponents();
        Dimension size = new Dimension(1019, 100);
        setSize(size);
        jt_maF.setText(phatSinhMaHD());
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setFont(new Font("JetBrains Mono", 0, 14));
        jTable1.getTableHeader().setBackground(new Color(255, 255, 255));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setBackground(new Color(255, 255, 255));
        jTable1.setSelectionMode(0);
        jb_hinhAnh.setBackground(color_bg);
        jb_sua.setBackground(color_bg);
        jb_them.setBackground(color_bg);
        jb_tim.setBackground(color_bg);
        jb_xuat.setBackground(color_bg);
        jb_xoa.setBackground(color_bg);
        PlaceholderSupport placeholderSupport = new PlaceholderSupport();
        placeholderSupport.addPlaceholder(jt_tim, " Nhập mã bàn để tìm kiếm");

        List<DanhMucMonAn> danhMucMonAn = DanhMucMonAnDAO.getDSLoaiSP();
        danhMuc = new HashMap<>();
        jComboBox_DM.setBackground(Color.WHITE);
        for (DanhMucMonAn i : danhMucMonAn) {
            jComboBox_DM.addItem(i.getTenDanhMuc());
            danhMuc.put(i.getTenDanhMuc(), i);
          
        }

    }

    public String phatSinhMaHD() {
        String characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder generatedString = new StringBuilder();

        Random random = new Random();
        for (int i = 0; i < 6; i++) {
            int index = random.nextInt(characters.length());
            generatedString.append(characters.charAt(index));
        }
        return generatedString.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_picture = new javax.swing.JPanel();
        l_hinhAnh = new javax.swing.JLabel();
        jb_hinhAnh = new javax.swing.JButton();
        jp_food = new javax.swing.JPanel();
        l_maF = new javax.swing.JLabel();
        l_moTa = new javax.swing.JLabel();
        l_DM = new javax.swing.JLabel();
        jt_maF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_moTa = new javax.swing.JTextArea();
        jt_gia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jComboBox_DM = new javax.swing.JComboBox<>();
        l_gia = new javax.swing.JLabel();
        l_tenF = new javax.swing.JLabel();
        jt_tenF = new javax.swing.JTextField();
        jp_button = new javax.swing.JPanel();
        jb_sua = new javax.swing.JButton();
        jb_xoa = new javax.swing.JButton();
        jb_xuat = new javax.swing.JButton();
        jb_them = new javax.swing.JButton();
        jp_table = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jt_tim = new javax.swing.JTextField();
        jb_tim = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1019, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_picture.setBackground(new java.awt.Color(255, 255, 255));
        jp_picture.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        l_hinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        l_hinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb_hinhAnh.setBackground(new java.awt.Color(22, 78, 180));
        jb_hinhAnh.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_hinhAnh.setForeground(new java.awt.Color(255, 255, 255));
        jb_hinhAnh.setText("CHỌN ẢNH");
        jb_hinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_hinhAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_pictureLayout = new javax.swing.GroupLayout(jp_picture);
        jp_picture.setLayout(jp_pictureLayout);
        jp_pictureLayout.setHorizontalGroup(
            jp_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pictureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jp_pictureLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jb_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_pictureLayout.setVerticalGroup(
            jp_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pictureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        add(jp_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 230, 250));

        jp_food.setBackground(new java.awt.Color(255, 255, 255));
        jp_food.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jp_food.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_maF.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_maF.setText("Mã món ăn:");
        jp_food.add(l_maF, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 34, 83, -1));

        l_moTa.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_moTa.setText("Mô tả:");
        jp_food.add(l_moTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 83, 30));

        l_DM.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_DM.setText("Danh mục:");
        jp_food.add(l_DM, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 83, 30));

        jt_maF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt_maF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jp_food.add(jt_maF, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 21, 210, 30));

        text_moTa.setColumns(1);
        text_moTa.setRows(3);
        text_moTa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jScrollPane1.setViewportView(text_moTa);

        jp_food.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 70));

        jt_gia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jp_food.add(jt_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 28, 179, 30));

        jComboBox_DM.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jComboBox_DM.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jComboBox_DM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DMActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(jComboBox_DM);

        jp_food.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 180, 30));

        l_gia.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_gia.setText("Giá tiền:");
        jp_food.add(l_gia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 83, 30));

        l_tenF.setBackground(new java.awt.Color(255, 255, 255));
        l_tenF.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        l_tenF.setText("Tên món ăn:");
        jp_food.add(l_tenF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 83, 30));

        jt_tenF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jp_food.add(jt_tenF, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 67, 210, 30));

        jp_button.setBackground(new java.awt.Color(255, 255, 255));

        jb_sua.setBackground(new java.awt.Color(22, 78, 180));
        jb_sua.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_sua.setForeground(new java.awt.Color(255, 255, 255));
        jb_sua.setText("SỬA");
        jb_sua.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suaActionPerformed(evt);
            }
        });

        jb_xoa.setBackground(new java.awt.Color(22, 78, 180));
        jb_xoa.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_xoa.setForeground(new java.awt.Color(255, 255, 255));
        jb_xoa.setText("XÓA");
        jb_xoa.setPreferredSize(new java.awt.Dimension(100, 50));

        jb_xuat.setBackground(new java.awt.Color(22, 78, 180));
        jb_xuat.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_xuat.setForeground(new java.awt.Color(255, 255, 255));
        jb_xuat.setText("XUẤT FILE");
        jb_xuat.setPreferredSize(new java.awt.Dimension(97, 27));

        jb_them.setBackground(new java.awt.Color(22, 78, 180));
        jb_them.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 0, 18)); // NOI18N
        jb_them.setForeground(new java.awt.Color(255, 255, 255));
        jb_them.setText("THÊM");
        jb_them.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_buttonLayout = new javax.swing.GroupLayout(jp_button);
        jp_button.setLayout(jp_buttonLayout);
        jp_buttonLayout.setHorizontalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jb_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jp_buttonLayout.setVerticalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_them, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jb_xuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jp_food.add(jp_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 709, 50));

        add(jp_food, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 760, 250));

        jp_table.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món ăn", "Tên món ăn", "Giá tiền", "Danh mục", "Hình ảnh", "Mô tả"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jt_tim.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jt_tim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb_tim.setBackground(new java.awt.Color(22, 78, 180));
        jb_tim.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jb_tim.setForeground(new java.awt.Color(255, 255, 255));
        jb_tim.setText("Tìm kiếm");
        jb_tim.setBorder(null);
        jb_tim.setPreferredSize(new java.awt.Dimension(30, 30));
        jb_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_tableLayout = new javax.swing.GroupLayout(jp_table);
        jp_table.setLayout(jp_tableLayout);
        jp_tableLayout.setHorizontalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addComponent(jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 196, Short.MAX_VALUE))
        );
        jp_tableLayout.setVerticalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        add(jp_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ MÓN ĂN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(340, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_DMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DMActionPerformed

    private void jb_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_timActionPerformed

    private void jb_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_suaActionPerformed

    private void jb_hinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_hinhAnhActionPerformed
        // Hiển thị JFileChooser để chọn ảnh
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);

        // Nếu người dùng chọn ảnh
        if (result == JFileChooser.APPROVE_OPTION) {
            // Lấy file ảnh đã chọn
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();

            // Tạo ImageIcon từ đường dẫn file ảnh
            ImageIcon icon = new ImageIcon(filePath);

            // Lấy ảnh từ ImageIcon và điều chỉnh kích thước để vừa với JLabel
            Image img = icon.getImage();
            Image imgScale = img.getScaledInstance(l_hinhAnh.getWidth(), l_hinhAnh.getHeight(), Image.SCALE_SMOOTH);

            // Tạo ImageIcon mới từ ảnh đã điều chỉnh kích thước
            ImageIcon scaledIcon = new ImageIcon(imgScale);

            // Hiển thị ảnh trên JLabel
            l_hinhAnh.setIcon(scaledIcon);

            // Lưu đường dẫn ảnh vào biến urlAnh
            urlAnh = filePath;
    }//GEN-LAST:event_jb_hinhAnhActionPerformed
    }
    private void jb_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_themActionPerformed
        try {
            // Lấy các giá trị từ giao diện
            String ma = jt_maF.getText();
            String ten = jt_tenF.getText();
            String mota = text_moTa.getText();
            var danhmuc = (String) jComboBox_DM.getSelectedItem();
            DanhMucMonAn DanhMuc = danhMuc.get(danhmuc);

            double gia;
            try {
                gia = Double.valueOf(jt_gia.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Giá tiền không hợp lệ! Vui lòng nhập số.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return; // Thoát khỏi hàm nếu giá không hợp lệ
            }

            // Thêm món ăn vào cơ sở dữ liệu
            MonAnDAO.themMonAn(MonAn.builder()
                    .maMonAn(ma)
                    .tenMonAn(ten)
                    .moTa(mota)
                    .giaTien(gia)
                    .danhMuc(DanhMuc)
                    .hinhAnh(urlAnh)
                    .build()
            );

            // Thông báo thêm thành công
            JOptionPane.showMessageDialog(this, "Thêm món ăn thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            // Thông báo lỗi
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }//GEN-LAST:event_jb_themActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_DM;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_hinhAnh;
    private javax.swing.JButton jb_sua;
    private javax.swing.JButton jb_them;
    private javax.swing.JButton jb_tim;
    private javax.swing.JButton jb_xoa;
    private javax.swing.JButton jb_xuat;
    private javax.swing.JPanel jp_button;
    private javax.swing.JPanel jp_food;
    private javax.swing.JPanel jp_picture;
    private javax.swing.JPanel jp_table;
    private javax.swing.JTextField jt_gia;
    private javax.swing.JTextField jt_maF;
    private javax.swing.JTextField jt_tenF;
    private javax.swing.JTextField jt_tim;
    private javax.swing.JLabel l_DM;
    private javax.swing.JLabel l_gia;
    private javax.swing.JLabel l_hinhAnh;
    private javax.swing.JLabel l_maF;
    private javax.swing.JLabel l_moTa;
    private javax.swing.JLabel l_tenF;
    private javax.swing.JTextArea text_moTa;
    // End of variables declaration//GEN-END:variables
}
