/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author ACER
 */
public class MonAnGUI extends javax.swing.JPanel {
    Color color_bg = Color.decode("#00405d");
    /**
     * Creates new form MonAn_GUI
     */
    public MonAnGUI() {
        initComponents();
        Dimension size = new Dimension(1019, 100);
        setSize(size);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(255, 255, 255));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setBackground(new Color(255, 255, 255));
        jTable1.setSelectionMode(0);
        jb_hinhAnh.setBackground(color_bg);
        jb_sua.setBackground(color_bg);
        jb_them.setBackground(color_bg);
        jb_tim.setBackground(color_bg);
        jb_xuat.setBackground(color_bg);
        jb_xoa.setBackground(color_bg);
        PlaceholderSupport placeholderSupport = new PlaceholderSupport();
        placeholderSupport.addPlaceholder(jt_tim," Nhập mã bàn để tìm kiếm");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_picture = new javax.swing.JPanel();
        l_hinhAnh = new javax.swing.JLabel();
        jb_hinhAnh = new javax.swing.JButton();
        jp_food = new javax.swing.JPanel();
        l_maF = new javax.swing.JLabel();
        l_moTa = new javax.swing.JLabel();
        l_DM = new javax.swing.JLabel();
        jt_maF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_moTa = new javax.swing.JTextArea();
        jt_gia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jComboBox_DM = new javax.swing.JComboBox<>();
        l_gia = new javax.swing.JLabel();
        l_tenF = new javax.swing.JLabel();
        jt_tenF = new javax.swing.JTextField();
        jp_button = new javax.swing.JPanel();
        jb_sua = new javax.swing.JButton();
        jb_xoa = new javax.swing.JButton();
        jb_xuat = new javax.swing.JButton();
        jb_them = new javax.swing.JButton();
        jp_table = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jt_tim = new javax.swing.JTextField();
        jb_tim = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(598, 100));

        jp_picture.setBackground(new java.awt.Color(255, 255, 255));
        jp_picture.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        l_hinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        l_hinhAnh.setForeground(new java.awt.Color(0, 0, 0));
        l_hinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb_hinhAnh.setBackground(new java.awt.Color(22, 78, 180));
        jb_hinhAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_hinhAnh.setForeground(new java.awt.Color(255, 255, 255));
        jb_hinhAnh.setText("CHỌN ẢNH");

        javax.swing.GroupLayout jp_pictureLayout = new javax.swing.GroupLayout(jp_picture);
        jp_picture.setLayout(jp_pictureLayout);
        jp_pictureLayout.setHorizontalGroup(
            jp_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pictureLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(l_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pictureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jp_pictureLayout.setVerticalGroup(
            jp_pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pictureLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(l_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jp_food.setBackground(new java.awt.Color(255, 255, 255));
        jp_food.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "QUẢN LÝ MÓN ĂN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        l_maF.setForeground(new java.awt.Color(0, 0, 0));
        l_maF.setText("Mã món ăn:");

        l_moTa.setForeground(new java.awt.Color(0, 0, 0));
        l_moTa.setText("Mô tả:");

        l_DM.setForeground(new java.awt.Color(0, 0, 0));
        l_DM.setText("Danh mục:");

        jt_maF.setBackground(new java.awt.Color(255, 255, 255));
        jt_maF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        text_moTa.setBackground(new java.awt.Color(255, 255, 255));
        text_moTa.setColumns(1);
        text_moTa.setRows(3);
        text_moTa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jScrollPane1.setViewportView(text_moTa);

        jt_gia.setBackground(new java.awt.Color(255, 255, 255));
        jt_gia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jComboBox_DM.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_DM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_DM.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jComboBox_DM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DMActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(jComboBox_DM);

        l_gia.setForeground(new java.awt.Color(0, 0, 0));
        l_gia.setText("Giá tiền:");

        l_tenF.setBackground(new java.awt.Color(255, 255, 255));
        l_tenF.setForeground(new java.awt.Color(0, 0, 0));
        l_tenF.setText("Tên món ăn:");

        jt_tenF.setBackground(new java.awt.Color(255, 255, 255));
        jt_tenF.setForeground(new java.awt.Color(0, 0, 0));
        jt_tenF.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jp_button.setBackground(new java.awt.Color(255, 255, 255));

        jb_sua.setBackground(new java.awt.Color(22, 78, 180));
        jb_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_sua.setForeground(new java.awt.Color(255, 255, 255));
        jb_sua.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\fix.png")); // NOI18N
        jb_sua.setText("SỬA");
        jb_sua.setPreferredSize(new java.awt.Dimension(100, 50));
        jb_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_suaActionPerformed(evt);
            }
        });

        jb_xoa.setBackground(new java.awt.Color(22, 78, 180));
        jb_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_xoa.setForeground(new java.awt.Color(255, 255, 255));
        jb_xoa.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\delete.png")); // NOI18N
        jb_xoa.setText("XÓA");
        jb_xoa.setPreferredSize(new java.awt.Dimension(100, 50));

        jb_xuat.setBackground(new java.awt.Color(22, 78, 180));
        jb_xuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_xuat.setForeground(new java.awt.Color(255, 255, 255));
        jb_xuat.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\xuatfile.png")); // NOI18N
        jb_xuat.setText("XUẤT");
        jb_xuat.setPreferredSize(new java.awt.Dimension(97, 27));

        jb_them.setBackground(new java.awt.Color(22, 78, 180));
        jb_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_them.setForeground(new java.awt.Color(255, 255, 255));
        jb_them.setIcon(new javax.swing.ImageIcon("C:\\QuanLyDatBan2\\QuanLyDatBan\\QuanLyDatBan\\icon\\add.png")); // NOI18N
        jb_them.setText("THÊM");
        jb_them.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jp_buttonLayout = new javax.swing.GroupLayout(jp_button);
        jp_button.setLayout(jp_buttonLayout);
        jp_buttonLayout.setHorizontalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jb_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jb_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jp_buttonLayout.setVerticalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_buttonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_them, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jp_foodLayout = new javax.swing.GroupLayout(jp_food);
        jp_food.setLayout(jp_foodLayout);
        jp_foodLayout.setHorizontalGroup(
            jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_foodLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_moTa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_tenF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_maF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jt_maF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jt_tenF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_foodLayout.createSequentialGroup()
                        .addComponent(l_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_foodLayout.createSequentialGroup()
                        .addComponent(l_DM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_foodLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jp_foodLayout.setVerticalGroup(
            jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_foodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_maF)
                    .addComponent(jt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_gia)
                    .addComponent(jt_maF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_foodLayout.createSequentialGroup()
                        .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_tenF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_tenF)
                            .addComponent(l_DM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_moTa))))
                .addGap(27, 27, 27)
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        jp_table.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã món ăn", "Tên món ăn", "Giá tiền", "Danh mục", "Hình ảnh", "Mô tả"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jt_tim.setBackground(new java.awt.Color(255, 255, 255));
        jt_tim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jb_tim.setBackground(new java.awt.Color(22, 78, 180));
        jb_tim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jb_tim.setForeground(new java.awt.Color(255, 255, 255));
        jb_tim.setText("Tìm kiếm");
        jb_tim.setBorder(null);
        jb_tim.setPreferredSize(new java.awt.Dimension(30, 30));
        jb_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_tableLayout = new javax.swing.GroupLayout(jp_table);
        jp_table.setLayout(jp_tableLayout);
        jp_tableLayout.setHorizontalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_tableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
        );
        jp_tableLayout.setVerticalGroup(
            jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_tableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_tim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jp_food, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jp_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jp_picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jp_food, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_DMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_DMActionPerformed

    private void jb_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_timActionPerformed

    private void jb_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_suaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_suaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_DM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_hinhAnh;
    private javax.swing.JButton jb_sua;
    private javax.swing.JButton jb_them;
    private javax.swing.JButton jb_tim;
    private javax.swing.JButton jb_xoa;
    private javax.swing.JButton jb_xuat;
    private javax.swing.JPanel jp_button;
    private javax.swing.JPanel jp_food;
    private javax.swing.JPanel jp_picture;
    private javax.swing.JPanel jp_table;
    private javax.swing.JTextField jt_gia;
    private javax.swing.JTextField jt_maF;
    private javax.swing.JTextField jt_tenF;
    private javax.swing.JTextField jt_tim;
    private javax.swing.JLabel l_DM;
    private javax.swing.JLabel l_gia;
    private javax.swing.JLabel l_hinhAnh;
    private javax.swing.JLabel l_maF;
    private javax.swing.JLabel l_moTa;
    private javax.swing.JLabel l_tenF;
    private javax.swing.JTextArea text_moTa;
    // End of variables declaration//GEN-END:variables
}
