/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import com.mycompany.quanlydatban.dao.HoaDonDAO;
import java.awt.BorderLayout;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Vo Van Tuong
 */
public class ThongKe_GUI extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe_GUI
     */
    public ThongKe_GUI() {
        initComponents();
        setLayout(new BorderLayout());
        add(jp_TT,BorderLayout.NORTH); 
        PlaceholderSupport placehodersupport = new PlaceholderSupport();
        placehodersupport.addPlaceholder(Jt_tim,"nhập năm cần thống kê");
//        int nam = Integer.parseInt(Jt_tim.getText().trim());
        map =hd_d.doanhThuTheoThang(2024);
        createDataset();
        ten= "Thống Kê Doanh Thu Theo Tháng Năm 2024";
        loai = "Tháng";
         chart = new ChartPanel(createChart());
        chart.setPreferredSize(new java.awt.Dimension(1170, 540));
        jp_BieuDo.setLayout(new BorderLayout());
        jp_BieuDo.add(chart);
        add(jp_BieuDo,BorderLayout.CENTER);
      
        
    }
    
  public JFreeChart createChart() {
        JFreeChart barChart = ChartFactory.createBarChart(
                ten,
                loai, "DoanhThu",
                createDataset(), PlotOrientation.VERTICAL, false, false, false);
        return barChart;
    }
  
  public CategoryDataset createDataset() {
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//         map = hd_d.doanhThuTheoThang();
        for(Entry<Integer,Double> entry: map.entrySet()){
            dataset.addValue(entry.getValue(),"Doanh Thu",entry.getKey());
        }
        return dataset;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_TT = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jlb_TT = new javax.swing.JLabel();
        Jt_tim = new javax.swing.JTextField();
        Jbt_XacNhan = new javax.swing.JButton();
        jp_BieuDo = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống Kê Theo Tháng", "Thống Kê Theo Năm" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jlb_TT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlb_TT.setText("THỐNG KÊ DOANH THU");

        Jt_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jt_timActionPerformed(evt);
            }
        });

        Jbt_XacNhan.setText("Xác nhận");
        Jbt_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbt_XacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_TTLayout = new javax.swing.GroupLayout(jp_TT);
        jp_TT.setLayout(jp_TTLayout);
        jp_TTLayout.setHorizontalGroup(
            jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TTLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jlb_TT)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(jp_TTLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jbt_XacNhan)
                .addContainerGap())
            .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_TTLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jp_TTLayout.setVerticalGroup(
            jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_TTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_TT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbt_XacNhan)
                    .addComponent(Jt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_TTLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        add(jp_TT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        jp_BieuDo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jp_BieuDoLayout = new javax.swing.GroupLayout(jp_BieuDo);
        jp_BieuDo.setLayout(jp_BieuDoLayout);
        jp_BieuDoLayout.setHorizontalGroup(
            jp_BieuDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        jp_BieuDoLayout.setVerticalGroup(
            jp_BieuDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        add(jp_BieuDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Thống Kê Theo Tháng"))
        {
            map = hd_d.doanhThuTheoThang(2024);
            ten = "Thống Kê Doanh Thu Theo Tháng Năm 2024";
            loai = "Tháng";
            Jt_tim.setEditable(true);
        }
        else if(jComboBox1.getSelectedItem().equals("Thống Kê Theo Năm"))
        {
            map = hd_d.doanhThuTheoNam();
            ten = "Thống Kê Doanh Thu Theo Năm";
            loai= "Năm"; 
            Jt_tim.setEditable(false);
        }
 
        createDataset();
        chart = new ChartPanel(createChart());
        jp_BieuDo.setLayout(new BorderLayout());
        jp_BieuDo.removeAll();
        jp_BieuDo.add(chart);
        jp_BieuDo.revalidate();
        jp_BieuDo.repaint();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Jbt_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbt_XacNhanActionPerformed
        // TODO add your handling code here:
        if(Jt_tim.getText().equals("nhập năm cần thống kê"))
        {
            map= hd_d.doanhThuTheoThang(2024);
            
        }
        else {
            int nam = Integer.parseInt(Jt_tim.getText().trim());
            map = hd_d.doanhThuTheoThang(nam);
        }
           ten = "Thống Kê Doanh Thu Theo Tháng "+ Jt_tim.getText().trim();
           loai = "Tháng";
        createDataset();
        chart= new ChartPanel(createChart());
        jp_BieuDo.setLayout(new BorderLayout());
        jp_BieuDo.removeAll();
        jp_BieuDo.add(chart);
        jp_BieuDo.revalidate();
        jp_BieuDo.repaint();
    }//GEN-LAST:event_Jbt_XacNhanActionPerformed

    private void Jt_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jt_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jt_timActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbt_XacNhan;
    private javax.swing.JTextField Jt_tim;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlb_TT;
    private javax.swing.JPanel jp_BieuDo;
    private javax.swing.JPanel jp_TT;
    // End of variables declaration//GEN-END:variables

   private HoaDonDAO hd_d = new HoaDonDAO();
    Map<Integer,Double> map = new HashMap<>();
    private String ten;
    private String loai;
    private ChartPanel chart;
}
