/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.quanlydatban.GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;


/**
 *
 * @author gunny
 */
public class HoaDonPanel extends javax.swing.JPanel {


    /**
     * Creates new form HoaDonPanel
     */
    public HoaDonPanel() {
        initComponents();
        Color color_bg = Color.decode("#00405d");
        setLayout(new BorderLayout());
        add(jp_TT,BorderLayout.NORTH);
        add(jp_Table,BorderLayout.CENTER);
        add(jPanel_Button,BorderLayout.SOUTH);
        jButtonTimKiem.setBackground(color_bg);
        btn_In.setBackground(color_bg);
        btn_ThanhToan.setBackground(color_bg);
        PlaceholderSupport placeholderSupport = new PlaceholderSupport();
        
        placeholderSupport.addPlaceholder(jTextFieldTimKiemTheoMaBan," Nhập mã bàn");
        placeholderSupport.addPlaceholder(jT_TimKiemTheoMaKH," Nhập mã khách hàng");
        placeholderSupport.addPlaceholder(jT_TimTheoSoDienThoai," Nhập số điện thoại");
        // 1. Thiết lập không cho phép chỉnh sửa ô
        JTable_DS.setDefaultEditor(Object.class, null);
        JTable_ChiTiet.setDefaultEditor(Object.class, null);
        // 2. Cho phép chọn dòng
        JTable_DS.setRowSelectionAllowed(true);
        JTable_DS.setColumnSelectionAllowed(false);
//        JTable_DS.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JTable_ChiTiet.setRowSelectionAllowed(true);
        JTable_ChiTiet.setColumnSelectionAllowed(false);
//        JTable_ChiTiet.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_TT = new javax.swing.JPanel();
        jLabelTimHoaDon = new javax.swing.JLabel();
        jTextFieldTimKiemTheoMaBan = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jL_TrangThai = new javax.swing.JLabel();
        jComboBox_TrangThai = new javax.swing.JComboBox<>();
        jL_TimTheoSoDienThoai = new javax.swing.JLabel();
        jL_TimTheoMa = new javax.swing.JLabel();
        jT_TimTheoSoDienThoai = new javax.swing.JTextField();
        jT_TimKiemTheoMaKH = new javax.swing.JTextField();
        jL_MaBan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jp_Table = new javax.swing.JPanel();
        jScrollPanelHoaDon = new javax.swing.JScrollPane();
        JTable_DS = new javax.swing.JTable();
        jPanel_Infor = new javax.swing.JPanel();
        jL_Tong = new javax.swing.JLabel();
        jL_Giam = new javax.swing.JLabel();
        jL_Thue = new javax.swing.JLabel();
        jL_ThanhToan = new javax.swing.JLabel();
        jT_Tong = new javax.swing.JTextField();
        jT_Giam = new javax.swing.JTextField();
        jT_Thue = new javax.swing.JTextField();
        jT_ThanhToan = new javax.swing.JTextField();
        jScrollPaneChiTietHoaDon = new javax.swing.JScrollPane();
        JTable_ChiTiet = new javax.swing.JTable();
        jPanel_Button = new javax.swing.JPanel();
        btn_In = new javax.swing.JButton();
        btn_ThanhToan = new javax.swing.JButton();
        btn_ThanhToan1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản Lý Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jp_TT.setBackground(new java.awt.Color(255, 255, 255));
        jp_TT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabelTimHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelTimHoaDon.setText("Tìm Hóa Đơn:");

        jTextFieldTimKiemTheoMaBan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldTimKiemTheoMaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimKiemTheoMaBanActionPerformed(evt);
            }
        });

        jButtonTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimKiem.setText("Tìm Kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jL_TrangThai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_TrangThai.setText("Trạng Thái:");

        jComboBox_TrangThai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã Thanh Toán", "Chưa Thanh Toán" }));
        jComboBox_TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TrangThaiActionPerformed(evt);
            }
        });

        jL_TimTheoSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_TimTheoSoDienThoai.setText("Theo Số Điện Thoại:");

        jL_TimTheoMa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_TimTheoMa.setText("Theo Mã Khách Hàng:");

        jT_TimTheoSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jT_TimKiemTheoMaKH.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jT_TimKiemTheoMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TimKiemTheoMaKHActionPerformed(evt);
            }
        });

        jL_MaBan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_MaBan.setText("Theo Mã Bàn:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Số Điện Thoại", "Email"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jp_TTLayout = new javax.swing.GroupLayout(jp_TT);
        jp_TT.setLayout(jp_TTLayout);
        jp_TTLayout.setHorizontalGroup(
            jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTimHoaDon)
                    .addGroup(jp_TTLayout.createSequentialGroup()
                        .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_TimTheoMa)
                            .addComponent(jL_TimTheoSoDienThoai)
                            .addComponent(jL_MaBan))
                        .addGap(18, 18, 18)
                        .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jT_TimTheoSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jComboBox_TrangThai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTimKiemTheoMaBan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_TimKiemTheoMaKH))
                        .addGap(29, 29, 29)
                        .addComponent(jButtonTimKiem))
                    .addComponent(jL_TrangThai))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );
        jp_TTLayout.setVerticalGroup(
            jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTimHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTimKiemTheoMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_MaBan)
                    .addComponent(jButtonTimKiem))
                .addGap(18, 18, 18)
                .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_TimTheoSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_TimTheoSoDienThoai))
                .addGap(18, 18, 18)
                .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_TimKiemTheoMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_TimTheoMa))
                .addGap(18, 18, 18)
                .addGroup(jp_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_TrangThai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_TrangThai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jp_Table.setBackground(new java.awt.Color(255, 255, 255));
        jp_Table.setPreferredSize(new java.awt.Dimension(400, 70));

        jScrollPanelHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPanelHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Danh Sách Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jScrollPanelHoaDon.setRequestFocusEnabled(false);

        JTable_DS.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JTable_DS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Ngày tạo", "Mã Bàn", "Thành Tiền", "Tình Trạng"
            }
        ));
        JTable_DS.setEnabled(false);
        JTable_DS.setIntercellSpacing(new java.awt.Dimension(5, 5));
        JTable_DS.setMinimumSize(new java.awt.Dimension(75, 0));
        JTable_DS.setPreferredSize(new java.awt.Dimension(0, 0));
        JTable_DS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_DSMouseClicked(evt);
            }
        });
        jScrollPanelHoaDon.setViewportView(JTable_DS);

        jPanel_Infor.setPreferredSize(new java.awt.Dimension(375, 200));

        jL_Tong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_Tong.setText("Tổng Tiền:");

        jL_Giam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_Giam.setText("Giảm Giá:");

        jL_Thue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_Thue.setText("Thuế:");

        jL_ThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jL_ThanhToan.setText("Số Tiền Cần Thanh Toán:");

        jT_Tong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jT_Tong.setEnabled(false);
        jT_Tong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TongActionPerformed(evt);
            }
        });

        jT_Giam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jT_Giam.setEnabled(false);

        jT_Thue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jT_Thue.setEnabled(false);

        jT_ThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jT_ThanhToan.setEnabled(false);

        javax.swing.GroupLayout jPanel_InforLayout = new javax.swing.GroupLayout(jPanel_Infor);
        jPanel_Infor.setLayout(jPanel_InforLayout);
        jPanel_InforLayout.setHorizontalGroup(
            jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_InforLayout.createSequentialGroup()
                        .addComponent(jL_ThanhToan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_InforLayout.createSequentialGroup()
                        .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Giam)
                            .addComponent(jL_Thue)
                            .addComponent(jL_Tong))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_Thue, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jT_Giam)
                            .addComponent(jT_Tong)))))
        );
        jPanel_InforLayout.setVerticalGroup(
            jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Tong)
                    .addComponent(jT_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Giam)
                    .addComponent(jT_Giam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Thue)
                    .addComponent(jT_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_ThanhToan)
                    .addComponent(jT_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneChiTietHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneChiTietHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chi Tiết Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jScrollPaneChiTietHoaDon.setPreferredSize(new java.awt.Dimension(800, 400));

        JTable_ChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số Thứ Tự", "Tên Món Ăn", "Đơn Giá", "Thành Tiền"
            }
        ));
        JTable_ChiTiet.setEnabled(false);
        JTable_ChiTiet.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPaneChiTietHoaDon.setViewportView(JTable_ChiTiet);

        javax.swing.GroupLayout jp_TableLayout = new javax.swing.GroupLayout(jp_Table);
        jp_Table.setLayout(jp_TableLayout);
        jp_TableLayout.setHorizontalGroup(
            jp_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TableLayout.createSequentialGroup()
                .addComponent(jScrollPanelHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneChiTietHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jPanel_Infor, javax.swing.GroupLayout.PREFERRED_SIZE, 361, Short.MAX_VALUE)))
        );
        jp_TableLayout.setVerticalGroup(
            jp_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_TableLayout.createSequentialGroup()
                        .addComponent(jScrollPaneChiTietHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Infor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPanelHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jPanel_Button.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Button.setPreferredSize(new java.awt.Dimension(586, 50));

        btn_In.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_In.setForeground(new java.awt.Color(255, 255, 255));
        btn_In.setText("In Hóa Đơn");
        btn_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InActionPerformed(evt);
            }
        });

        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        btn_ThanhToan1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btn_ThanhToan1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan1.setText("Xem Chi Tiết");
        btn_ThanhToan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ButtonLayout = new javax.swing.GroupLayout(jPanel_Button);
        jPanel_Button.setLayout(jPanel_ButtonLayout);
        jPanel_ButtonLayout.setHorizontalGroup(
            jPanel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ButtonLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btn_ThanhToan1)
                .addGap(18, 18, 18)
                .addComponent(btn_ThanhToan)
                .addGap(18, 18, 18)
                .addComponent(btn_In)
                .addContainerGap(891, Short.MAX_VALUE))
        );
        jPanel_ButtonLayout.setVerticalGroup(
            jPanel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThanhToan)
                    .addComponent(btn_In)
                    .addComponent(btn_ThanhToan1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 1435, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_Table, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE))
                        .addGap(458, 458, 458)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jp_TT.getAccessibleContext().setAccessibleName("Hoa Don");
        jp_Table.getAccessibleContext().setAccessibleName("QUẢN LÝ HÓA ĐƠN");
        jp_Table.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTimKiemTheoMaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemTheoMaBanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldTimKiemTheoMaBanActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void btn_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_InActionPerformed

    private void jComboBox_TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TrangThaiActionPerformed

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void jT_TongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_TongActionPerformed

    private void btn_ThanhToan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThanhToan1ActionPerformed

    private void JTable_DSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_DSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JTable_DSMouseClicked

    private void jT_TimKiemTheoMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TimKiemTheoMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_TimKiemTheoMaKHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_ChiTiet;
    private javax.swing.JTable JTable_DS;
    private javax.swing.JButton btn_In;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_ThanhToan1;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JComboBox<String> jComboBox_TrangThai;
    private javax.swing.JLabel jL_Giam;
    private javax.swing.JLabel jL_MaBan;
    private javax.swing.JLabel jL_ThanhToan;
    private javax.swing.JLabel jL_Thue;
    private javax.swing.JLabel jL_TimTheoMa;
    private javax.swing.JLabel jL_TimTheoSoDienThoai;
    private javax.swing.JLabel jL_Tong;
    private javax.swing.JLabel jL_TrangThai;
    private javax.swing.JLabel jLabelTimHoaDon;
    private javax.swing.JPanel jPanel_Button;
    private javax.swing.JPanel jPanel_Infor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneChiTietHoaDon;
    private javax.swing.JScrollPane jScrollPanelHoaDon;
    private javax.swing.JTextField jT_Giam;
    private javax.swing.JTextField jT_ThanhToan;
    private javax.swing.JTextField jT_Thue;
    private javax.swing.JTextField jT_TimKiemTheoMaKH;
    private javax.swing.JTextField jT_TimTheoSoDienThoai;
    private javax.swing.JTextField jT_Tong;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldTimKiemTheoMaBan;
    private javax.swing.JPanel jp_TT;
    private javax.swing.JPanel jp_Table;
    // End of variables declaration//GEN-END:variables
}
